package wfes;

import validation.*;
import to.*;
import dal.*;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.List;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 01
 */
public class EmployeeDetail extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployee
     */
    Employee employee = null;

    public EmployeeDetail() {
        initComponents();
        clear();

        fillComboDataDept(DeptCB);
        fillComboDataDsgn(DsgnCB);
        fillComboDataTeam(TeamCB);

    }

    public EmployeeDetail(Employee employee) {
        initComponents();
        clear();
        fillComboDataDept(DeptCB);
        fillComboDataDsgn(DsgnCB);
        fillComboDataTeam(TeamCB);

        this.employee = employee;
        EmpNameTF.setText(employee.getEmpName());
        MobileNoTF.setText(employee.getMobileNo().toString());
        EmailIdTF.setText(employee.getEmailId());
        dobDC.setDate(employee.getDob());
        QualificationTF.setText(employee.getQualification());
        UsernameTF.setText(employee.getUsername());
//        PasswordPF.setText(employee.getPassword());
        AddressTA.setText(employee.getAddress());
        joinDateDC.setDate(employee.getJoinDate());
        CityTF.setText(employee.getCity());
        int itemCountDept = DeptCB.getItemCount();
        for (int i = 0; i < itemCountDept; i++) {
            if (DeptCB.getItemAt(i).toString().equals(employee.getDeptId() + "")) {
                DeptCB.setSelectedIndex(i);
            }
        }
        int itemCountDsgn = DsgnCB.getItemCount();
        for (int i = 0; i < itemCountDsgn; i++) {
            if (DsgnCB.getItemAt(i).toString().equals(employee.getDsgnId() + "")) {
                DsgnCB.setSelectedIndex(i);
            }
        }
        int itemCountTeam = TeamCB.getItemCount();
        System.out.println(employee.getTeamId());
        for (int i = 0; i < itemCountTeam; i++) {
            if (TeamCB.getItemAt(i).toString().equals(employee.getTeamId() + "")) {
                TeamCB.setSelectedIndex(i);
            }
        }
        if(employee.getGender()==1){
            maleRB.setSelected(true);
        }
        else if(employee.getGender() == 2){
            femaleRB.setSelected(true);
        }

        maleRB.setEnabled(false);
        femaleRB.setEnabled(false);
        EmpNameTF.setEditable(false);
        MobileNoTF.setEditable(false);
        EmailIdTF.setEditable(false);
        //dobDC.setEditable(false);
        dobDC.setEnabled(false);
        DeptCB.setEnabled(false);
        DsgnCB.setEnabled(false);
        TeamCB.setEnabled(false);
        
        ProjectLeaderCB.setVisible(false);
        ProjectLeaderLB.setVisible(false);
        ProjectLeaderVal.setVisible(false);
        UsernameVal.setVisible(false);

        QualificationTF.setEditable(false);
        UsernameTF.setEditable(false);
//        PasswordPF.setEditable(false);
        AddressTA.setEditable(false);
        //joinDateDC.setEditable(false);
        joinDateDC.setEnabled(false);
        CityTF.setEditable(false);
        DeptCB.setEditable(false);
        DsgnCB.setEditable(false);
        TeamCB.setEditable(false);
      //  jLabel15.setVisible(false);
      //  PasswordPF.setVisible(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(250, 0), new java.awt.Dimension(250, 0), new java.awt.Dimension(250, 32767));
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        EmpNameVal = new javax.swing.JLabel();
        EmpNameTF = new javax.swing.JTextField();
        AddressVal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressTA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        femaleRB = new javax.swing.JRadioButton();
        genderLB = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CityTF = new javax.swing.JTextField();
        dobDC = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        dobVal = new javax.swing.JLabel();
        CityVal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        maleRB = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        EmailIdTF = new javax.swing.JTextField();
        EmailIdVal1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        EmailIdVal2 = new javax.swing.JLabel();
        MobileNoVal2 = new javax.swing.JLabel();
        MobileNoVal1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MobileNoTF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        QualificationTF = new javax.swing.JTextField();
        ProjectLeaderLB = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        joinDateDC = new com.toedter.calendar.JDateChooser();
        JoinDateVal = new javax.swing.JLabel();
        TeamLB = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DeptCB = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        TeamVal = new javax.swing.JLabel();
        ProjectLeaderCB = new javax.swing.JComboBox();
        ProjectLeaderVal = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TeamCB = new javax.swing.JComboBox();
        DsgnVal = new javax.swing.JLabel();
        DeptVal = new javax.swing.JLabel();
        QualificationVal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DsgnCB = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        UsernameTF = new javax.swing.JTextField();
        UsernameVal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(86, 86, 87));
        jLabel13.setText("Employee Details");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EmpNameVal.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        EmpNameVal.setForeground(new java.awt.Color(255, 0, 0));
        EmpNameVal.setText("EmpNameVal");

        EmpNameTF.setFocusAccelerator('E');
        EmpNameTF.setFocusCycleRoot(true);
        EmpNameTF.setFocusTraversalPolicyProvider(true);

        AddressVal.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        AddressVal.setForeground(new java.awt.Color(255, 0, 0));
        AddressVal.setText("AddressVal");

        AddressTA.setColumns(20);
        AddressTA.setRows(5);
        AddressTA.setFocusTraversalPolicyProvider(true);
        jScrollPane1.setViewportView(AddressTA);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel1.setText("Employee Name :");

        jLabel16.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(86, 86, 87));
        jLabel16.setText("Personal Details");

        femaleRB.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        femaleRB.setText("Female");
        femaleRB.setFocusTraversalPolicyProvider(true);

        genderLB.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        genderLB.setText("Gender :");

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel7.setText("City :");

        CityTF.setFocusTraversalPolicyProvider(true);

        dobDC.setFocusTraversalPolicyProvider(true);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel4.setText("Date Of Birth :");

        dobVal.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        dobVal.setForeground(new java.awt.Color(255, 0, 0));
        dobVal.setText("dobVal");

        CityVal.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        CityVal.setForeground(new java.awt.Color(255, 0, 0));
        CityVal.setText("CityVal");

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel6.setText("Address :");

        maleRB.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        maleRB.setText("Male");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderLB))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(maleRB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(femaleRB))
                                .addComponent(CityTF)
                                .addComponent(EmpNameVal, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AddressVal, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CityVal, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dobVal, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                            .addComponent(EmpNameTF)
                            .addComponent(dobDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel16))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(EmpNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dobVal)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLB)
                            .addComponent(maleRB)
                            .addComponent(femaleRB)))
                    .addComponent(EmpNameVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressVal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addComponent(CityVal)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel3.setText("Email_ID :");

        EmailIdTF.setFocusTraversalPolicyProvider(true);

        EmailIdVal1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        EmailIdVal1.setForeground(new java.awt.Color(255, 0, 0));
        EmailIdVal1.setText("EmailIDVal1");

        jLabel17.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(86, 86, 87));
        jLabel17.setText("Contact Details");

        EmailIdVal2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        EmailIdVal2.setForeground(new java.awt.Color(255, 0, 0));
        EmailIdVal2.setText("EmailIdVal2");

        MobileNoVal2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        MobileNoVal2.setForeground(new java.awt.Color(255, 0, 0));
        MobileNoVal2.setText("MobileNoVal2");

        MobileNoVal1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        MobileNoVal1.setForeground(new java.awt.Color(255, 0, 0));
        MobileNoVal1.setText("MobileNoVal1");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel2.setText("Mobile No :");

        MobileNoTF.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailIdVal1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailIdVal2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailIdTF)
                            .addComponent(MobileNoTF)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MobileNoVal2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MobileNoVal1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MobileNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MobileNoVal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MobileNoVal2)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailIdVal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailIdVal2)
                .addGap(51, 51, 51))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        QualificationTF.setFocusTraversalPolicyProvider(true);

        ProjectLeaderLB.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 11)); // NOI18N
        ProjectLeaderLB.setText("Project Leader:");

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel5.setText("Qualification :");

        joinDateDC.setFocusTraversalPolicyProvider(true);

        JoinDateVal.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        JoinDateVal.setForeground(new java.awt.Color(255, 0, 0));
        JoinDateVal.setText("JoinDateVal");

        TeamLB.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        TeamLB.setText("Team :");

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel8.setText("Join Date :");

        DeptCB.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        DeptCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DeptCB.setFocusTraversalPolicyProvider(true);

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel9.setText("Department :");

        TeamVal.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        TeamVal.setForeground(new java.awt.Color(255, 0, 0));
        TeamVal.setText("TeamVal");

        ProjectLeaderCB.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        ProjectLeaderCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProjectLeaderCB.setFocusTraversalPolicyProvider(true);

        ProjectLeaderVal.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        ProjectLeaderVal.setForeground(new java.awt.Color(255, 0, 0));
        ProjectLeaderVal.setText("ProjectLeaderVal");

        jLabel19.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(86, 86, 87));
        jLabel19.setText("Organizational Details");

        TeamCB.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        TeamCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TeamCB.setFocusTraversalPolicyProvider(true);

        DsgnVal.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        DsgnVal.setForeground(new java.awt.Color(255, 0, 0));
        DsgnVal.setText("DsgnVal");

        DeptVal.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        DeptVal.setForeground(new java.awt.Color(255, 0, 0));
        DeptVal.setText("DeptVal");

        QualificationVal.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        QualificationVal.setForeground(new java.awt.Color(255, 0, 0));
        QualificationVal.setText("QualificationVal");

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel10.setText("Designation :");

        DsgnCB.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        DsgnCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DsgnCB.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(QualificationVal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JoinDateVal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(QualificationTF)
                                            .addComponent(joinDateDC, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)))
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DeptCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(DeptVal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 3, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TeamLB, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(ProjectLeaderLB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TeamCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ProjectLeaderCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ProjectLeaderVal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TeamVal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(DsgnVal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DsgnCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(QualificationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(QualificationVal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinDateDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JoinDateVal)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeptCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeptVal)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DsgnCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DsgnVal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeamCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeamLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeamVal)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjectLeaderLB)
                    .addComponent(ProjectLeaderCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProjectLeaderVal)
                .addGap(19, 19, 19))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(86, 86, 87));
        jLabel18.setText("Login Details");

        UsernameTF.setFocusTraversalPolicyProvider(true);

        UsernameVal.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        UsernameVal.setForeground(new java.awt.Color(255, 0, 0));
        UsernameVal.setText("UsernameVal");

        jLabel14.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel14.setText("Username:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameTF)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(UsernameVal)
                                .addGap(0, 245, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(9, 9, 9)
                .addComponent(UsernameVal)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(172, 172, 172))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressTA;
    private javax.swing.JLabel AddressVal;
    private javax.swing.JTextField CityTF;
    private javax.swing.JLabel CityVal;
    private javax.swing.JComboBox DeptCB;
    private javax.swing.JLabel DeptVal;
    private javax.swing.JComboBox DsgnCB;
    private javax.swing.JLabel DsgnVal;
    private javax.swing.JTextField EmailIdTF;
    private javax.swing.JLabel EmailIdVal1;
    private javax.swing.JLabel EmailIdVal2;
    private javax.swing.JTextField EmpNameTF;
    private javax.swing.JLabel EmpNameVal;
    private javax.swing.JLabel JoinDateVal;
    private javax.swing.JTextField MobileNoTF;
    private javax.swing.JLabel MobileNoVal1;
    private javax.swing.JLabel MobileNoVal2;
    private javax.swing.JComboBox ProjectLeaderCB;
    private javax.swing.JLabel ProjectLeaderLB;
    private javax.swing.JLabel ProjectLeaderVal;
    private javax.swing.JTextField QualificationTF;
    private javax.swing.JLabel QualificationVal;
    private javax.swing.JComboBox TeamCB;
    private javax.swing.JLabel TeamLB;
    private javax.swing.JLabel TeamVal;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JLabel UsernameVal;
    private com.toedter.calendar.JDateChooser dobDC;
    private javax.swing.JLabel dobVal;
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel genderLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser joinDateDC;
    private javax.swing.JRadioButton maleRB;
    // End of variables declaration//GEN-END:variables
    void fillComboDataDept(JComboBox jComboBox) {
        Vector vector = new Vector();
        List<Department> departmentList = new DepartmentDAL().getDepartmentDetails();
        Department departmentTempFinal = null;
        for (Department departmentTemp : departmentList) {

            vector.add(departmentTemp);

        }
        ComboBoxModel cbm = new DefaultComboBoxModel(vector);
        jComboBox.setModel(cbm);

    }

    void fillComboDataDsgn(JComboBox jComboBox) {
        Vector vector = new Vector();
        List<Designation> designationList = new DesignationDAL().getDesignationDetails();
        Designation designationTempFinal = null;
        for (Designation designationTemp : designationList) {

            vector.add(designationTemp);

        }
        ComboBoxModel cbm = new DefaultComboBoxModel(vector);
        jComboBox.setModel(cbm);

    }

    void fillComboDataTeam(JComboBox jComboBox) {
        Vector vector = new Vector();
        List<Team> teamList = new TeamDAL().getTeamDetails();
        Team teamTempFinal = null;
        for (Team teamTemp : teamList) {

            System.out.println(teamTemp);
            vector.add(teamTemp);

        }
        ComboBoxModel cbm = new DefaultComboBoxModel(vector);
        jComboBox.setModel(cbm);

    }
    FocusListener fl = new FocusListener() {
        @Override
        public void focusGained(FocusEvent e) {
            throw new UnsupportedOperationException("Not supported yet.");
        }

        @Override
        public void focusLost(FocusEvent e) {
            throw new UnsupportedOperationException("Not supported yet.");
        }
    };

    void clear() {
        EmpNameVal.setText("");
        MobileNoVal1.setText("");
        MobileNoVal2.setText("");
        EmailIdVal1.setText("");
        EmailIdVal2.setText("");
        dobVal.setText("");
        QualificationVal.setText("");
        AddressVal.setText("");
        JoinDateVal.setText("");
        DeptVal.setText("");
        DsgnVal.setText("");
        TeamVal.setText("");
        CityVal.setText("");
    }

    boolean validation() {
        boolean flag = true;
        clear();

        if (EmpNameTF.getText().equals("")) {
            EmpNameVal.setText("Please enter Employee Name");
            flag = false;
        }
        if (MobileNoTF.getText().equals("")) {
            MobileNoVal1.setText("Please enter Mobile No");
            flag = false;
        }
        if (!MobileNoTF.getText().equals("") && !(new MobileValidator().validate(MobileNoTF.getText()))) {
            MobileNoVal2.setText("Please enter valid Mobile No");
            flag = false;
        }

        if (EmailIdTF.getText().equals("")) {
            EmailIdVal1.setText("Please enter Email Id");
            flag = false;
        }
        if (!EmailIdTF.getText().equals("") && !(new EmailValidator().validate(EmailIdTF.getText()))) {
            EmailIdVal2.setText("Please enter valid Email");
            flag = false;
        }
        if (dobDC.getDate() == null) {
            dobVal.setText("Please enter Date Of Birth");
            flag = false;
        }
        if (QualificationTF.getText().equals("")) {
            QualificationVal.setText("Please enter Qualification");
            flag = false;
        }
        if (AddressTA.getText().equals("")) {
            AddressVal.setText("Please enter Address");
            flag = false;
        }
        if (CityTF.getText().equals("")) {
            CityVal.setText("Please enter City");
            flag = false;
        }

        if (joinDateDC.getDate() == null) {
            JoinDateVal.setText("Please enter Joining Date");
            flag = false;
        }
        if (DeptCB.getSelectedIndex() == -1) {
            DeptVal.setText("Please enter Department");
            flag = false;
        }
        if (DsgnCB.getSelectedIndex() == -1) {
            DsgnVal.setText("Please enter Designation");
            flag = false;
        }
        if (TeamCB.getSelectedIndex() == -1) {
            TeamVal.setText("Please enter Team");
            flag = false;
        }


        return flag;
    }
}
