/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wfes;

import dal.SpyModuleDAL;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import to.SpyModule;
import wfes.Monitor;

/**
 *
 * @author sai
 */
public class OpenScreenshot extends javax.swing.JPanel {

    private BufferedImage image;

    /**
     * Creates new form OpenScreenshot
     */
    public OpenScreenshot(SpyModule spymod) {

        initComponents();

        List<SpyModule> spymod1 = null;
        spymod1 = new SpyModuleDAL().getSpyModuleIMAGEDetails();
        //System.out.println("after get method"+spymod1.get(wfes.Monitor.returnSelectedRow()).getEmpId().getEmpId());
        
        for (SpyModule requestemp : spymod1) {
           // if (requestemp.getEmpId().getEmpId() == 15 && requestemp.getSpId() == 250) {

                Icon i = new ImageIcon(requestemp.getFile());
                imageLB.setIcon(i);
         //   }
        }




        // Icon i = new ImageIcon("C:/Users/sai/Pictures/Result.png");



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLB = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLB, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLB, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLB;
    // End of variables declaration//GEN-END:variables
}
